name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 42 */4 * * *

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd ~/gamer_news/spider && ./spider/run_spider.sh
    